name: codemirror_element
version: 0.0.3+4.12.0
author: DartLab.org <pub@dartlab.org>
description: Polymer element wrapping the CodeMirror text editor.
homepage: https://github.com/dartlab/codemirror-element
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  codemirror: '>=0.1.6+4.12.0 <0.2.0'
  polymer: '>=0.15.0 <0.16.0'
dev_dependencies:
  unittest: any
transformers:
- polymer:
    entry_points: 
    - example/simple_example.html
    - test/codemirror_test.html